// <auto-generated />
using System;
using Backend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Backend.Core.Models.Appointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutcomeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symptoms")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = "appt1",
                            Cost = 350000m,
                            Date = new DateTime(2025, 6, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = "doc1",
                            Notes = "Initial checkup",
                            PatientId = "patient1",
                            Status = 0,
                            Symptoms = "Đau ngực nhẹ, khó thở khi vận động"
                        },
                        new
                        {
                            Id = "appt2",
                            Cost = 300000m,
                            Date = new DateTime(2025, 6, 11, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = "doc1",
                            Notes = "Đã kê đơn thuốc hạ sốt và kháng sinh",
                            OutcomeStatus = 0,
                            PatientId = "patient1",
                            Status = 1,
                            Symptoms = "Sốt cao, ho khan"
                        });
                });

            modelBuilder.Entity("Backend.Core.Models.AppointmentPatientReview", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppointmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("AppointmentPatientReviews");
                });

            modelBuilder.Entity("Backend.Core.Models.Doctor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AvgRating")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalAppointments")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = "doc1",
                            Availability = "{\"2025-06-17\":[\"09:00\",\"10:00\",\"11:00\",\"14:00\"],\"2025-06-18\":[\"09:30\",\"10:30\",\"15:00\"]}",
                            AvgRating = 4.5m,
                            ConsultationFee = 350000m,
                            ExperienceYears = 12,
                            Location = "Phòng Khám Tim Mạch Trung Tâm, 123 Đường Sức Khỏe",
                            Specialty = "Tim Mạch",
                            TotalAppointments = 150
                        });
                });

            modelBuilder.Entity("Backend.Core.Models.DoctorReview", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorReviews");

                    b.HasData(
                        new
                        {
                            Id = "drev1_doc1",
                            Comment = "Bác sĩ rất tận tâm và chuyên nghiệp.",
                            Date = new DateTime(2025, 6, 9, 10, 0, 0, 0, DateTimeKind.Utc),
                            DoctorId = "doc1",
                            PatientName = "Nguyễn Văn A",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("Backend.Core.Models.Medication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dosage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            Id = "med1_appt2",
                            AppointmentId = "appt2",
                            Dosage = "500mg",
                            Duration = "3 ngày",
                            Frequency = "Ngày 2 lần",
                            Name = "Paracetamol"
                        },
                        new
                        {
                            Id = "med2_appt2",
                            AppointmentId = "appt2",
                            Dosage = "250mg",
                            Duration = "5 ngày",
                            Frequency = "Ngày 3 lần",
                            Name = "Amoxicillin"
                        });
                });

            modelBuilder.Entity("Backend.Core.Models.Relative", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Relatives");

                    b.HasData(
                        new
                        {
                            Id = "rel1_patient1",
                            Name = "Nguyễn Văn B",
                            Phone = "0901234567",
                            Relationship = "Con",
                            UserId = "patient1"
                        });
                });

            modelBuilder.Entity("Backend.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Allergies")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "patient1",
                            AvatarUrl = "https://placehold.co/100x100.png?text=AP",
                            Email = "alice@example.com",
                            Name = "Alice Patient",
                            PasswordHash = "dummy_hash",
                            Salt = "dummy_salt",
                            Type = 2
                        },
                        new
                        {
                            Id = "doc1",
                            AvatarUrl = "https://placehold.co/120x120.png?text=EC",
                            Email = "emily.carter@example.com",
                            Name = "BS. Emily Carter",
                            PasswordHash = "dummy_hash",
                            Salt = "dummy_salt",
                            Type = 1
                        },
                        new
                        {
                            Id = "admin1",
                            AvatarUrl = "https://placehold.co/100x100.png?text=AD",
                            Email = "admin@example.com",
                            Name = "Admin User",
                            PasswordHash = "dummy_hash",
                            Salt = "dummy_salt",
                            Type = 0
                        });
                });

            modelBuilder.Entity("Backend.Core.Models.UserNotification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelatedLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotifications");

                    b.HasData(
                        new
                        {
                            Id = "notif1_patient1",
                            Context = "Lịch hẹn của bạn vào 10:00 ngày mai đã được xác nhận.",
                            DateTime = new DateTime(2025, 6, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            RelatedLink = "/appointments",
                            Type = "appointment_confirmed",
                            UserId = "patient1"
                        });
                });

            modelBuilder.Entity("Backend.Core.Models.Appointment", b =>
                {
                    b.HasOne("Backend.Core.Models.User", "Doctor")
                        .WithMany("DoctorAppointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Core.Models.User", "Patient")
                        .WithMany("PatientAppointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Backend.Core.Models.AppointmentPatientReview", b =>
                {
                    b.HasOne("Backend.Core.Models.Appointment", "Appointment")
                        .WithOne("PatientReview")
                        .HasForeignKey("Backend.Core.Models.AppointmentPatientReview", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Backend.Core.Models.Doctor", b =>
                {
                    b.HasOne("Backend.Core.Models.User", "User")
                        .WithOne("DoctorProfile")
                        .HasForeignKey("Backend.Core.Models.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Core.Models.DoctorReview", b =>
                {
                    b.HasOne("Backend.Core.Models.Doctor", "Doctor")
                        .WithMany("Reviews")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Backend.Core.Models.Medication", b =>
                {
                    b.HasOne("Backend.Core.Models.Appointment", "Appointment")
                        .WithMany("Prescription")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Backend.Core.Models.Relative", b =>
                {
                    b.HasOne("Backend.Core.Models.User", "User")
                        .WithMany("Relatives")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Core.Models.UserNotification", b =>
                {
                    b.HasOne("Backend.Core.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Core.Models.Appointment", b =>
                {
                    b.Navigation("PatientReview");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Backend.Core.Models.Doctor", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Backend.Core.Models.User", b =>
                {
                    b.Navigation("DoctorAppointments");

                    b.Navigation("DoctorProfile");

                    b.Navigation("Notifications");

                    b.Navigation("PatientAppointments");

                    b.Navigation("Relatives");
                });
#pragma warning restore 612, 618
        }
    }
}
